/** Host-neutral speculative runtime surface. Pi adapters live in the root and extension entries. */
export {
	type ActionProjectionCoverage,
	type ActionProjectionRule,
	READ_RANGE_ACTION_KEY_PROJECTOR,
	READ_RANGE_COVERAGE_DETAILS_KEY,
	type ReadRangeCoverage,
	readRangesShareInFlight,
} from "./action-key-projection.ts";
export {
	type ActionEffect,
	type ActionKey,
	type ActionKeyMatch,
	type ActionKeyProjector,
	type ActionSemanticsDefinition,
	ActionSemanticsRegistry,
	actionKeyCovers,
	actionKeyMatch,
	actionKeyMatches,
	buildActionKey,
	type CanonicalAction,
	type ExactActionKeyMatch,
	PI_ACTION_SEMANTICS,
	type ProjectedActionKey,
	type ProjectedActionKeyMatch,
	type ResourceDependencyScope,
} from "./action-semantics.ts";
export type { DrafterToolDefinition } from "./common.ts";
export type {
	CandidateEventDescriptor,
	CandidateExecutionProjection,
	SpeculativeActionEvent,
	SpeculativeCacheSnapshot,
} from "./events.ts";
export {
	effectCapabilitiesCover,
	effectRequirements,
	type EffectCapabilities,
	type EffectCapability,
	type EffectRequirements,
	normalizeEffectRequirements,
	RESOURCE_OBSERVATION_EFFECTS,
	UNRESTRICTED_PROCESS_EFFECTS,
	WORKSPACE_PATH_MUTATION_EFFECTS,
} from "./effect-model.ts";
export {
	type EffectTransaction,
	EffectTransactionCoordinator,
	type EffectTransactionAttempt,
	type EffectTransactionDescriptor,
	type EffectTransactionState,
} from "./effect-transaction.ts";
export {
	type CapturedExecutionWorldResult,
	emptyWorldReuseMetrics,
	type ExecutionWorld,
	type ExecutionWorldDiagnosticReport,
	type ExecutionWorldDiagnosticSnapshot,
	type ExecutionWorldDiagnosticsContext,
	type ExecutionWorldObservation,
	type ExecutionWorldOperation,
	type ExecutionWorldOperationDiagnostic,
	type ExecutionCapabilityStatus,
	type ExecutionWorldHealthState,
	type ExecutionWorldPreparation,
	type ExecutionWorldRequest,
	ExecutionWorldRouter,
	executionCapabilityStatus,
	type ExecutionScope,
	type ExecutionWorldStorageControl,
	type ExecutionWorldStorageSnapshot,
	type ExecutionWorldScope,
	type ExecutionWorldSpeculation,
	type SpeculativeExecution,
	type SpeculativeExecutionRoute,
	sameSpeculativeExecutionRoute,
	type WorldBranch,
	type WorldCheckpoint,
	type WorldCommitMetrics,
	WorldCommitRejectedError,
	type WorldCompatibilityEvidence,
	type WorldExecutionMetrics,
	type WorldReuseMetrics,
	type WorldReuseStrategy,
	type WorldResultCapture,
} from "./execution-world.ts";
export {
	type AuthoritativeExecutionHooks,
	type AuthoritativeExecutionSettlement,
	type AuthoritativeToolExecutor,
	ToolExecutionGateway,
	type ToolExecutionContextFactory,
	type ToolExecutionRequirement,
	type ToolOperation,
} from "./tool-execution-gateway.ts";
export type {
	MaterializedPlan,
	PlanAction,
	PlanActionDependency,
	PlanActionDependencyCondition,
	PlanDelta,
	PlanProposal,
	PlanUpdate,
} from "./plan-proposal.ts";
export {
	captureResourceVersion,
	closeResourceVersionManagers,
	type ResourceChangeSet,
	type ResourceDependency,
	type ResourceValidationMetrics,
	ResourceVersionManager,
	type ResourceVersionToken,
	type ResourceVersionValidation,
	releaseResourceVersion,
	resourceDependencies,
	validateResourceVersion,
	watchResourceVersion,
} from "./resource-version.ts";
export {
	type AuthoritativeResultCapture,
	type CandidatePreflight,
	type ActorActionFeedback,
	type PredictionFeedback,
	candidateExecutionMs,
	candidateToolNames,
	diagnosticAction,
	diagnosticJson,
	makeSpeculativeActionRuntime,
	redactDiagnostics,
	type SpeculativeActionRuntime,
	type SpeculativeActionRuntimeAdapter,
	type SpeculativeActionSettings,
	type SpeculativeCandidate,
	type SpeculativeDraftCandidate,
	type MaterializedActorAction,
	type MaterializedSpeculativeCandidate,
	type SpeculativePlanSource,
	type SpeculativeRuntimeInspection,
} from "./runtime.ts";
export {
	type ActorActionIdentity,
	type ActorActionProvider,
	type ActorActionSettlement,
	type ActorHitTiming,
	type CandidateRejection,
	cause,
	type PlanActionIdentity,
	type PredictionAdoption,
	type PredictionIdentity,
	type PredictionSettlement,
	type ResolutionCause,
	type ResolutionStage,
	type ResourceValidation,
	type SettledSourceRequest,
	type SourceRequestIdentity,
	type SourceRequestKind,
	type SourceRequestSettlement,
	type ValidationMetrics,
	zeroValidationMetrics,
} from "./settlement.ts";
export { measureSpeculativeTask, type SpeculativeTaskTiming, type TimelineInterval } from "./task-timing.ts";
export {
	emptySpeculativeTraceSummary,
	reduceSpeculativeTrace,
	type SpeculativeTraceSummary,
	summarizeSpeculativeTrace,
} from "./trace-summary.ts";
