export {
	type ActionProjectionCoverage,
	type ActionProjectionRule,
	READ_RANGE_ACTION_KEY_PROJECTOR,
	READ_RANGE_COVERAGE_DETAILS_KEY,
	type ReadRangeCoverage,
	readRangesShareInFlight,
} from "./action-key-projection.ts";
export {
	type ActionEffect,
	type ActionKey,
	type ActionKeyMatch,
	type ActionKeyMismatchReason,
	type ActionKeyProjector,
	type ActionSemanticsDefinition,
	ActionSemanticsRegistry,
	actionKeyCovers,
	actionKeyMatch,
	actionKeyMatches,
	actionKeyMismatchReason,
	actionKeyProjectionPartitions,
	actionKeyProjects,
	buildActionKey,
	buildPiActionKey,
	type CanonicalAction,
	type ExactActionKeyMatch,
	FIND_DEFAULT_LIMIT,
	GREP_DEFAULT_LIMIT,
	inferredActionEffect,
	KEYABLE_TOOLS,
	LS_DEFAULT_LIMIT,
	normalizeReadLimit,
	normalizeReadOffset,
	normalizeRelativeRoot,
	OBSERVATION_ACTION_TOOLS,
	PI_ACTION_SEMANTICS,
	type ProjectedActionKey,
	type ProjectedActionKeyMatch,
	READ_DEFAULT_LIMIT,
	READ_DEFAULT_OFFSET,
	type ReadActionRange,
	type ResourceDependencyScope,
	readActionRange,
	UNBOUNDED_ACTION_TOOLS,
	WORKSPACE_MUTATION_ACTION_TOOLS,
} from "./action-semantics.ts";
export {
	createResourceSnapshotExecutionWorld,
	type SpeculativeAgentExecutionWorld,
	type SpeculativeToolExecutionContext,
} from "./agent-execution-world.ts";
export {
	type CreateSpeculativeActionHostOptions,
	createSpeculativeActionHost,
	type DraftOptionsContext,
	patternPlanActionID,
	type SpeculativeActionHost,
	type SpeculativeAgentPreflightContext,
	type SpeculativeAgentSettingsInput,
} from "./agent-integration.ts";
export {
	buildSingleToolCallPrompt,
	clampCandidateLimit,
	DEFAULTS,
	type DrafterToolDefinition,
	type LegacySpeculativeToolGroups,
	normalizeSpeculativeToolSelection,
	type SpeculativeToolSelectionInput,
	usageTokenCount,
} from "./common.ts";
export type {
	CandidateEventDescriptor,
	CandidateExecutionProjection,
	SpeculativeActionEvent,
	SpeculativeCacheSnapshot,
} from "./events.ts";
export {
	type ActionReuseKind,
	type ExecutionWorld,
	type ExecutionWorldPreparation,
	type ExecutionWorldRequest,
	ExecutionWorldRouter,
	type ExecutionWorldScope,
	type SpeculativeExecution,
	type SpeculativeExecutionRoute,
	sameSpeculativeExecutionRoute,
	type WorldBranch,
	type WorldBranchState,
	type WorldCheckpoint,
	type WorldCommitMetrics,
	type WorldCompatibilityEvidence,
	type WorldExecutionMetrics,
} from "./execution-world.ts";
export {
	createSpeculativeActionExtension,
	type EffectiveSpeculativeActionSettings,
	formatSpeculativeActionEvent,
	formatSpeculativeActionStatus,
	normalizeSpeculativeActionSettings,
	resolveSpeculativeDraftModel,
	type SpeculativeActionExtensionDependencies,
	type SpeculativeActionMetrics,
	type SpeculativeSettingsStore,
} from "./extension.ts";
export {
	acquirePatternAwareStore,
	applyBindings,
	applyBindingsPartial,
	applyBindingsPartialVariants,
	applyBindingsVariants,
	asPatternAwareRuntimeContext,
	inferBindings,
	PATTERN_AWARE_DEFAULTS,
	type PatternAwareActionSemantics,
	type PatternAwareBinding,
	type PatternAwareCandidate,
	type PatternAwareContinuation,
	type PatternAwareDependency,
	type PatternAwareDependencySource,
	type PatternAwareEvent,
	type PatternAwareEventInput,
	type PatternAwareEventSignature,
	type PatternAwareFeedback,
	type PatternAwareObservation,
	type PatternAwarePath,
	type PatternAwarePattern,
	type PatternAwareRuntimeContext,
	type PatternAwareSettings,
	PatternAwareStore,
	type PatternAwareStoreLease,
	patternAwareAnalyzerKey,
	patternAwarePersistenceFile,
	patternAwareRuntimeContext,
	patternAwareSettings,
	projectPatternAwareObservation,
} from "./pattern-aware.ts";
export {
	PI_READ_RANGE_PROJECTION_RULE,
	withPiProjectionCoverage,
	withPiReadCoverage,
} from "./pi-read-projection.ts";
export { type PiToolInvocationOptions, resolvePiToolInvocation } from "./pi-tool-invocation.ts";
export type {
	MaterializedPlan,
	PlanAction,
	PlanActionDependency,
	PlanActionDependencyCondition,
	PlanDelta,
	PlanProposal,
	PlanUpdate,
} from "./plan-proposal.ts";
export {
	captureResourceVersion,
	closeResourceVersionManagers,
	isResourceVersionToken,
	type ResourceChangeSet,
	type ResourceDependency,
	type ResourceValidationMetrics,
	ResourceVersionManager,
	type ResourceVersionToken,
	type ResourceVersionValidation,
	releaseResourceVersion,
	resourceDependencies,
	validateResourceVersion,
	watchResourceVersion,
} from "./resource-version.ts";
export {
	type CandidatePreflight,
	candidateExecutionMs,
	candidateToolNames,
	diagnosticAction,
	diagnosticJson,
	makeSpeculativeActionRuntime,
	redactDiagnostics,
	type SpeculativeActionRuntime,
	type SpeculativeActionRuntimeAdapter,
	type SpeculativeActionSettings,
	type SpeculativeCandidate,
	type SpeculativeDraftCandidate,
	type SpeculativePlanSource,
	type SpeculativeRuntimeInspection,
} from "./runtime.ts";
export {
	type SpeculativeActionPackageSettings,
	SpeculativeActionSettingsStore,
	type SpeculativeSettingsScope,
} from "./settings-store.ts";
export {
	type ActorActionIdentity,
	type ActorActionProvider,
	type ActorActionSettlement,
	type ActorHitTiming,
	type CandidateRejection,
	cause,
	type PlanActionIdentity,
	type PredictionAdoption,
	type PredictionIdentity,
	type PredictionSettlement,
	type ResolutionCause,
	type ResolutionStage,
	type ResourceValidation,
	type SettledSourceRequest,
	type SourceRequestIdentity,
	type SourceRequestKind,
	type SourceRequestSettlement,
	type ValidationMetrics,
	zeroValidationMetrics,
} from "./settlement.ts";
export { measureSpeculativeTask, type SpeculativeTaskTiming, type TimelineInterval } from "./task-timing.ts";
export type { ToolInvocation, ToolProcessInvocation, ToolSettlement } from "./tool-settlement.ts";
export {
	emptySpeculativeTraceSummary,
	reduceSpeculativeTrace,
	type SpeculativeTraceSummary,
	summarizeSpeculativeTrace,
} from "./trace-summary.ts";
export {
	closeWorkspaceSandboxPools,
	commitSandboxDelta,
	createWorkspaceSandbox,
	type PrepareSandboxWorkspaceOptions,
	prepareSandboxWorkspace,
	type SandboxExecutionDelta,
	type SandboxFileChange,
	type SandboxWorkspaceContext,
	type WorkspaceSandboxOptions,
	withSandboxWorkspace,
} from "./workspace-sandbox.ts";
