export {
	BenefitGate,
	type BenefitDecision,
	type BenefitDecisionReason,
	type BenefitGatePolicy,
	type BenefitGateSnapshot,
	type BenefitObservation,
	DEFAULT_BENEFIT_GATE_POLICY,
	ForkBenefitGate,
	type ForkBenefitDecision,
	type ForkBenefitDecisionReason,
	type ForkBenefitGatePolicy,
	type ForkBenefitGateSnapshot,
	type ForkBenefitObservation,
} from "./fork-benefit-gate.ts";
export {
	type ActionProjectionCoverage,
	type ActionProjectionRule,
	READ_RANGE_ACTION_KEY_PROJECTOR,
	READ_RANGE_COVERAGE_DETAILS_KEY,
	type ReadRangeCoverage,
	readRangesShareInFlight,
} from "./action-key-projection.ts";
export {
	type ActionEffect,
	type ActionKey,
	type ActionKeyMatch,
	type ActionKeyMismatchReason,
	type ActionKeyProjector,
	type ActionSemanticsDefinition,
	ActionSemanticsRegistry,
	actionKeyCovers,
	actionKeyMatch,
	actionKeyMatches,
	actionKeyMismatchReason,
	actionKeyProjectionPartitions,
	actionKeyProjects,
	BASH_TAIL_LINES_ACTION_KEY_PROJECTOR,
	type BashTailLinesView,
	bashTailLinesView,
	buildActionKey,
	buildPiActionKey,
	type CanonicalAction,
	type ExactActionKeyMatch,
	FIND_DEFAULT_LIMIT,
	GREP_DEFAULT_LIMIT,
	inferredActionEffect,
	KEYABLE_TOOLS,
	LS_DEFAULT_LIMIT,
	normalizeReadLimit,
	normalizeReadOffset,
	normalizeRelativeRoot,
	OBSERVATION_ACTION_TOOLS,
	PI_ACTION_SEMANTICS,
	type ProjectedActionKey,
	type ProjectedActionKeyMatch,
	READ_DEFAULT_LIMIT,
	READ_DEFAULT_OFFSET,
	type ReadActionRange,
	type ResourceDependencyScope,
	readActionRange,
	UNBOUNDED_ACTION_TOOLS,
	WORKSPACE_MUTATION_ACTION_TOOLS,
} from "./action-semantics.ts";
export {
	createResourceSnapshotExecutionWorld,
	type SpeculativeAgentExecutionWorld,
	type SpeculativeToolExecutionContext,
} from "./agent-execution-world.ts";
export {
	type ActionDrafterGateSnapshot,
	type CreateSpeculativeActionHostOptions,
	createSpeculativeActionHost,
	type DraftOptionsContext,
	patternPlanActionID,
	type SpeculativeActionHost,
	type SpeculativeAgentPreflightContext,
	type SpeculativeAgentSettingsInput,
} from "./agent-integration.ts";
export {
	clampCandidateLimit,
	DEFAULTS,
	type DrafterToolDefinition,
	type LegacySpeculativeToolGroups,
	normalizeSpeculativeToolSelection,
	type SpeculativeToolSelectionInput,
	usageTokenCount,
} from "./common.ts";
export type {
	CandidateEventDescriptor,
	CandidateExecutionProjection,
	SpeculativeActionEvent,
	SpeculativeCacheSnapshot,
} from "./events.ts";
export {
	effectCapabilitiesCover,
	effectRequirements,
	type EffectCapabilities,
	type EffectCapability,
	type EffectRequirements,
	normalizeEffectRequirements,
	RESOURCE_OBSERVATION_EFFECTS,
	UNRESTRICTED_PROCESS_EFFECTS,
	WORKSPACE_PATH_MUTATION_EFFECTS,
} from "./effect-model.ts";
export {
	type EffectTransaction,
	EffectTransactionCoordinator,
	type EffectTransactionAttempt,
	type EffectTransactionDescriptor,
	type EffectTransactionState,
} from "./effect-transaction.ts";
export {
	type ArtifactReference,
	certificateReplayable,
	createExecPrototype,
	dependencyPathsetKey,
	type DependencyRole,
	digestObject,
	type DynamicDependency,
	type DynamicDependencyCertificate,
	type ExecPrototype,
	type ExitOutcome,
	type InheritedFileDescriptor,
	isSha256Digest,
	type OrderedEffectEvent,
	parseProcessCertificate,
	type ProcessPrototypeInput,
	type ProcessProvenanceCertificate,
	type ProcessResultRecord,
	PROCESS_CERTIFICATE_VERSION,
	processStrongKey,
	processWeakKey,
	type ProvenanceTaint,
	referencedArtifacts,
	sealProcessCertificate,
	type SemanticEnvironmentEntry,
	sha256Digest,
	type Sha256Digest,
} from "./provenance-certificate.ts";
export {
	captureAbsenceDependency,
	captureDirectoryDependency,
	captureFileDependency,
	captureSymlinkDependency,
	type DynamicDependencyValidation,
	type ProvenanceValidation,
	type ProvenanceValidationContext,
	validateDynamicDependencyCertificate,
	validateProcessCertificate,
} from "./provenance-validation.ts";
export {
	type MemoryReuseProvider,
	type ProcessReuseMissReason,
	type ProcessReusePlan,
	ProcessReusePlanner,
	type ProcessReuseRequest,
	type ReplayObservationContract,
} from "./reuse-planner.ts";
export { ArtifactCAS, ProvenanceCertificateStore, type VerifiedArtifactClosure } from "./reuse-store.ts";
export {
	type CapturedExecutionWorldResult,
	type ActionReuseKind,
	type ExecutionWorld,
	type ExecutionWorldPreparation,
	type ExecutionWorldRequest,
	ExecutionWorldRouter,
	type ExecutionWorldScope,
	type SpeculativeExecution,
	type SpeculativeExecutionRoute,
	sameSpeculativeExecutionRoute,
	type WorldBranch,
	type WorldBranchState,
	type WorldCheckpoint,
	type WorldCommitMetrics,
	type WorldCompatibilityEvidence,
	type WorldExecutionMetrics,
	type WorldReuseStrategy,
	type WorldResultCapture,
} from "./execution-world.ts";
export {
	type AuthoritativeToolExecutor,
	ToolExecutionGateway,
	type ToolExecutionContextFactory,
	type ToolExecutionRequirement,
	type ToolOperation,
} from "./tool-execution-gateway.ts";
export {
	createSpeculativeActionExtension,
	type EffectiveSpeculativeActionSettings,
	formatSpeculativeActionEvent,
	formatSpeculativeActionStatus,
	normalizeSpeculativeActionSettings,
	resolveSpeculativeDraftModel,
	type SpeculativeActionExtensionDependencies,
	type SpeculativeActionMetrics,
	type SpeculativeSettingsStore,
} from "./extension.ts";
export {
	acquirePatternAwareStore,
	applyBindings,
	applyBindingsVariants,
	asPatternAwareRuntimeContext,
	inferBindings,
	PATTERN_AWARE_DEFAULTS,
	type PatternAwareActionSemantics,
	type PatternAwareBinding,
	type PatternAwareCandidate,
	type PatternAwareContinuation,
	type PatternAwareDependency,
	type PatternAwareDependencySource,
	type PatternAwareEvent,
	type PatternAwareEventInput,
	type PatternAwareEventSignature,
	type PatternAwareFeedback,
	type PatternAwareObservation,
	type PatternAwarePath,
	type PatternAwarePattern,
	type PatternAwareRuntimeContext,
	type PatternAwareSettings,
	PatternAwareStore,
	type PatternAwareStoreLease,
	patternAwareAnalyzerKey,
	patternAwarePersistenceFile,
	patternAwareRuntimeContext,
	patternAwareSettings,
	projectPatternAwareObservation,
} from "./pattern-aware.ts";
export { PI_BASH_TAIL_LINES_PROJECTION_RULE } from "./pi-bash-projection.ts";
export {
	PI_READ_RANGE_PROJECTION_RULE,
	withPiProjectionCoverage,
	withPiReadCoverage,
} from "./pi-read-projection.ts";
export { type PiToolInvocationOptions, resolvePiToolInvocation } from "./pi-tool-invocation.ts";
export {
	LinuxProcessReuseBackend,
	type LinuxProcessBackendOptions,
	type LinuxProcessBackendStatus,
	type LinuxProcessReuseMetrics,
	type LinuxProcessSession,
} from "./linux-process-backend.ts";
export {
	createLinuxProcessExecutionWorld,
	type LinuxProcessExecutionWorldOptions,
} from "./linux-process-world.ts";
export {
	adaptProcessToolOperations,
	ProcessExecutionCoordinator,
	type ProcessExecutionRequest,
	type ProcessExecutionResult,
	type ProcessExecutor,
	type ProcessToolOperations,
} from "./process-execution.ts";
export type {
	MaterializedPlan,
	PlanAction,
	PlanActionDependency,
	PlanActionDependencyCondition,
	PlanDelta,
	PlanProposal,
	PlanUpdate,
} from "./plan-proposal.ts";
export {
	captureResourceVersion,
	closeResourceVersionManagers,
	isResourceVersionToken,
	type ResourceChangeSet,
	type ResourceDependency,
	type ResourceValidationMetrics,
	ResourceVersionManager,
	type ResourceVersionToken,
	type ResourceVersionValidation,
	releaseResourceVersion,
	resourceDependencies,
	validateResourceVersion,
	watchResourceVersion,
} from "./resource-version.ts";
export {
	type AuthoritativeResultCapture,
	type CandidatePreflight,
	type ActorActionFeedback,
	type PredictionFeedback,
	candidateExecutionMs,
	candidateToolNames,
	diagnosticAction,
	diagnosticJson,
	makeSpeculativeActionRuntime,
	redactDiagnostics,
	type SpeculativeActionRuntime,
	type SpeculativeActionRuntimeAdapter,
	type SpeculativeActionSettings,
	type SpeculativeCandidate,
	type SpeculativeDraftCandidate,
	type MaterializedActorAction,
	type MaterializedSpeculativeCandidate,
	type SpeculativePlanSource,
	type SpeculativeRuntimeInspection,
} from "./runtime.ts";
export {
	normalizeSelfSpeculationSettings,
	SELF_SPECULATION_DEFAULTS,
	SelfSpeculationCoordinator,
	type SelfSpeculationCoordinatorOptions,
	type SelfSpeculationCoordinatorSnapshot,
	type SelfSpeculationForkTransport,
	type SelfSpeculationSettings,
	type SelfSpeculationSettingsInput,
	type SelfSpeculationVerificationOutcome,
	type SelfSpeculationVerificationStep,
} from "./self-speculation.ts";
export {
	SelfSpeculationActionBridge,
	type SelfSpeculationActionBatch,
	type SelfSpeculationActionCandidate,
	type SelfSpeculationActionCall,
	type SelfSpeculationActionEvidence,
} from "./self-speculation-action-bridge.ts";
export {
	type SpeculativeActionPackageSettings,
	SpeculativeActionSettingsStore,
	type SpeculativeSettingsScope,
} from "./settings-store.ts";
export {
	type ActorActionIdentity,
	type ActorActionProvider,
	type ActorActionSettlement,
	type ActorHitTiming,
	type CandidateRejection,
	cause,
	type PlanActionIdentity,
	type PredictionAdoption,
	type PredictionIdentity,
	type PredictionSettlement,
	type ResolutionCause,
	type ResolutionStage,
	type ResourceValidation,
	type SettledSourceRequest,
	type SourceRequestIdentity,
	type SourceRequestKind,
	type SourceRequestSettlement,
	type ValidationMetrics,
	zeroValidationMetrics,
} from "./settlement.ts";
export { measureSpeculativeTask, type SpeculativeTaskTiming, type TimelineInterval } from "./task-timing.ts";
export type { ToolInvocation, ToolProcessInvocation, ToolSettlement } from "./tool-settlement.ts";
export {
	emptySpeculativeTraceSummary,
	reduceSpeculativeTrace,
	type SpeculativeTraceSummary,
	summarizeSpeculativeTrace,
} from "./trace-summary.ts";
export {
	closeWorkspaceSandboxPools,
	commitSandboxDelta,
	createWorkspaceSandbox,
	type PrepareSandboxWorkspaceOptions,
	prepareSandboxWorkspace,
	readSandboxDirectoryState,
	type SandboxDirectoryChange,
	type SandboxDirectoryState,
	type SandboxExecutionDelta,
	type SandboxFileChange,
	type SandboxWorkspaceChange,
	type SandboxWorkspaceContext,
	type SandboxWorkspaceBranchOptions,
	type WorkspaceSandboxOptions,
	type WorkspaceSandboxDriver,
	forkSandboxWorkspace,
	withSandboxWorkspace,
	workspaceSandboxFingerprint,
} from "./workspace-sandbox.ts";
export {
	linuxOverlayfsCapability,
	mountLinuxOverlayfs,
	type LinuxOverlayfsCapability,
	type LinuxOverlayfsMount,
	type LinuxOverlayfsOptions,
} from "./linux-overlayfs.ts";
export type {
	WorkspaceRegularDelta,
	WorkspaceTransactionCapture,
	WorkspaceTransactionDelta,
	WorkspaceTransactionDriver,
} from "./workspace-transaction.ts";
