/** Provenance, planning, and content-addressed storage without any Pi host dependency. */
export {
	type ArtifactReference,
	certificateReplayable,
	createExecPrototype,
	dependencyPathsetKey,
	type DependencyRole,
	digestObject,
	type DynamicDependency,
	type DynamicDependencyCertificate,
	type ExecPrototype,
	type ExitOutcome,
	type InheritedFileDescriptor,
	isSha256Digest,
	type OrderedEffectEvent,
	parseProcessCertificate,
	type ProcessPrototypeInput,
	type ProcessProvenanceCertificate,
	type ProcessResultRecord,
	PROCESS_CERTIFICATE_VERSION,
	processStrongKey,
	processWeakKey,
	type ProvenanceTaint,
	referencedArtifacts,
	sealProcessCertificate,
	type SemanticEnvironmentEntry,
	sha256Digest,
	type Sha256Digest,
} from "./provenance-certificate.ts";
export {
	captureAbsenceDependency,
	captureDirectoryDependency,
	captureFileDependency,
	captureSymlinkDependency,
	type DynamicDependencyValidation,
	type ProvenanceValidation,
	type ProvenanceValidationContext,
	validateDynamicDependencyCertificate,
	validateProcessCertificate,
} from "./provenance-validation.ts";
export {
	type MemoryReuseProvider,
	type ProcessReuseLookupMetrics,
	type ProcessReuseMissReason,
	type ProcessReusePlan,
	ProcessReusePlanner,
	type ProcessReuseRequest,
	type ReplayObservationContract,
} from "./reuse-planner.ts";
export { ArtifactCAS, ProvenanceCertificateStore, type VerifiedArtifactClosure } from "./reuse-store.ts";
